name : Hello World

on: 
    push:

jobs: 
    hello-wold : 
        runs-on: windows-latest
        steps: 
          - name : Checkout 
            uses : actions/checkout@v4
          - name : Setup pnpm 
            uses : pnpm/action-setup@v2.4.0
            with : 
              version : 8
              run_installs : false  
            
         
          - name : install dependences
            run: pnpm install
          - name : Build
            run : pnpm run build
