name : Hello World

on: 
    push:

jobs: 
    hello-wold : 
        runs-on: windows-latest
        steps: 
          - name : Checkout 
            uses : actions/checkout@v4

          - name: Setup Bun
            uses: oven-sh/setup-bun@v1
            with:
              version : 8
              run_install : false
            
            
         
          - name : install dependences
            run: bun install
          - name : Build
            run : bun run build
